### ISSUE TITLE
Where is the Char2wav in your implementation ?

### ISSUE THREAD

**Issue by mazzzystar** [karanvivekbhargava/obamanet#1]
I read the paper and the author said, he used Char2wav to train the audio to make `using obama's voice to speak other words`, but I didn't find this part of **using Obama's voice to train text2voice**, could you help to find that ?

**Comment by karanvivekbhargava** [comment]
Hey @fancoo this project was finished in approximately three weeks. Hence I didn't have the time to make all the models. I do plan to do it later.

**Comment by lvZic** [comment]
> Hey @fancoo this project was finished in approximately three weeks. Hence I didn't have the time to make all the models. I do plan to do it later.

hi, have u added the Char2wav part yet?

**Comment by mazzzystar** [comment]
@lvZic sorry I didn't finished that in this project.
But there are a lot of methods to construct a text2voice for a specific person, such as [Tacotron](https://github.com/NVIDIA/tacotron2).

**Comment by lvZic** [comment]
> @lvZic sorry I didn't finished that in this project. But there are a lot of methods to construct a text2voice for a specific person, such as [Tacotron](https://github.com/NVIDIA/tacotron2).

thanks, Tacotron can do it too. Actually, what  I need is the Vocoder feature, and I will have a look.
