### ISSUE TITLE
How to train with GPU ?

### ISSUE THREAD

**Issue by Pawankhatri2k13** [karanvivekbhargava/obamanet#11]
After all processing, my training has started but on CPU, I want to train it on multiple GPUs..
Please, pull some requests.

Regards.

**Comment by duyvk** [comment]
probably because of your library installation. Try to uninstall tensorflow-gpu and install it again. It happens sometimes

**Comment by karanvivekbhargava** [comment]
Hey @Pawankhatri2k13 believe you got the answer from @duyvk
