### ISSUE TITLE
How to create .pkl files for own data set.

### ISSUE THREAD

**Issue by Pawankhatri2k13** [karanvivekbhargava/obamanet#12]
I am using this model for own videos, pix2pix.py training has been completed which generates .data, .index and .meta model files but cannot run train.py for keras models due to no pkl files.

Kindly help me in generating  data/audio_kp/audio_kp1467_mel.pickle, data/pca/pkp1467.pickle and data/pca/pca1467.pickle files used in train.py.

**Comment by Pawankhatri2k13** [comment]
I've created all above mentioned .pkl files with processing.py code, but now stuck in how to generate kp_test.pkl file.

Kindly help in this regard.

**Comment by wanshun123** [comment]
In https://drive.google.com/drive/folders/1QDRCWmqr87E3LWmYztqE7cpBZ3fALo-x?usp=sharing there is a file `processing.py` which generates these files.

**Comment by Pawankhatri2k13** [comment]
but it is still not cleared that how to prepare "a2key_data" folder and specially the file "kp_test.pickle" .
There is nothing in "processing.py" to create this file.
I've read this pickle file with Python and seen Numpy arrays against each image in "images/" folder, but unable to understand that how to create these Numpy arrays as they are also not simply image to Numpy converted arrays.

Please help in this regard.

**Comment by wanshun123** [comment]
Looks like it's in the `prepare_test_video.py` file.

**Comment by DrHaqkiem** [comment]
> but it is still not cleared that how to prepare "a2key_data" folder and specially the file "kp_test.pickle" .
> There is nothing in "processing.py" to create this file.
> I've read this pickle file with Python and seen Numpy arrays against each image in "images/" folder, but unable to understand that how to create these Numpy arrays as they are also not simply image to Numpy converted arrays.
> 
> Please help in this regard.

hi sir Pawankhatri2k13, did you manage to generate the kp_test.pickle file from prepare_test_video.py ?
I got an error says **IndexError: index 1 is out of bounds for axis 1 with size 1**

If possible may i look into how you organize your dataset?
