### ISSUE TITLE
When will the full code be released?

### ISSUE THREAD

**Issue by 7aughing** [karanvivekbhargava/obamanet#3]
Hi~

Thanks for your code, but I found the code is incomplete. When will the full code be released? And where can I find the **c/train** data?

**Comment by karanvivekbhargava** [comment]
Hi @duantiantian ,

What you're talking about is the data which is used for the training for the pix2pix network. I'm guessing that you're training for a different type of data altogether. So you would have to get the input and output pictures and stack them side by side. I hope this helps. If not then I can elaborate on it more.
