### ISSUE TITLE
vid2wav.py and tool folder

### ISSUE THREAD

**Issue by lusensama** [karanvivekbhargava/obamanet#5]
Hello there! I am not able to find the` vid2wav.py` and `tool/process.py` here. Is there a master branch somewhere else?

Tools found in Pix2pix repository

**Comment by babyjie57** [comment]
@lusensama Hi, do you find the vid2wav.py file?

**Comment by shliang0603** [comment]
@babyjie57  你有找到vid2wav.py  这个文件吗，我找了好久也没有找到，求助呀

**Comment by babyjie57** [comment]
@shliang0603 这个在data/processing.py里面的extract_audio函数里实现了。

**Comment by shliang0603** [comment]
@babyjie57 谢谢你哥哥，函数extrct_audio只是做的是从视频中提取语音吧，论文中提到的Char2eWav是从text到Audio，这个在这里没有实现吧，其实我特别想知道Char2Wav能不能实现从中文到语音的转换，我应用一下这部分看能不能实现从中文文本转语音，求指导
