### ISSUE TITLE
The number of files in 'data/processing.py'

### ISSUE THREAD

**Issue by lusensama** [karanvivekbhargava/obamanet#7]
Hello, I'm trying to retrain the network from scratch and I want to use the '`processing.py`' from data folder downloaded from the link.

However, at line 205
`		numOfFiles = 1467 # First 20 videos`
I want to know how is this number been calculated in order to create a correct pickle file for the `train.py` file to train.
Thank you!

**Comment by karanvivekbhargava** [comment]
Hi @lusensama ,
Thanks for trying the code out, as for your question, this was determined by how the data was chunked into various subfiles. The parts where the person was not saying anything meaningful was chopped off.
