### ISSUE TITLE
low resolution/blurry output

### ISSUE THREAD

**Issue by wanshun123** [karanvivekbhargava/obamanet#9]
Is there a way to improve the result at https://github.com/karanvivekbhargava/obamanet/blob/master/results/key2im.gif so the mouth area is high resolution like the rest of the picture?

**Comment by karanvivekbhargava** [comment]
Hey @wanshun123

I trained the pix2pix on just a subsample of the original dataset. Provided you train with more data, it can get much better at reproducing the lips at a good resolution.
